zero_calibration:
  captured_at: '2026-09-29T07:32:58.533401+00:00'
  side: right
  interface: can0
  samples: 100
  std_deg:
  - 0.0
  - 0.0109
  - 0.0
  - 0.0
  - 0.0
  - 0.0022
  - 0.0
  span_deg:
  - 0.0
  - 0.0219
  - 0.0
  - 0.0
  - 0.0
  - 0.0219
  - 0.0
robot:
  urdf_to_motor:
    right:
      sign:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      offset_deg:
      - 0.1639
      - -0.8196
      - -0.7541
      - -4.4916
      - 2.8086
      - -4.2949
      - 4.5135
